export const nagarikMessages: Record<string, Record<string, string>> = {
  hi: { "Choose language": "भाषा चुनें", "Open workspace": "वर्कस्पेस खोलें", "Profile settings": "प्रोफ़ाइल सेटिंग्स", "Profile": "प्रोफ़ाइल", "Log out": "लॉग आउट", "Log in": "लॉग इन", "Create account": "खाता बनाएं", "Find my possible benefits": "मेरे संभावित लाभ खोजें", "How it works": "यह कैसे काम करता है", "Explore schemes": "योजनाएं देखें", "Benefit navigator": "लाभ मार्गदर्शक", "Myself": "मेरे लिए", "For Someone Else": "किसी और के लिए", "Situation": "स्थिति", "Documents": "दस्तावेज़", "Continue": "जारी रखें", "Previous": "पिछला", "Building your plan": "आपकी योजना बन रही है", "Your situation": "आपकी स्थिति", "Their situation": "उनकी स्थिति", "Documents you have": "आपके पास मौजूद दस्तावेज़", "Answer what you know.": "जो जानकारी है, वह बताएं।" },
  mr: { "Choose language": "भाषा निवडा", "Open workspace": "वर्कस्पेस उघडा", "Profile settings": "प्रोफाइल सेटिंग्ज", "Profile": "प्रोफाइल", "Log out": "लॉग आउट", "Log in": "लॉग इन", "Create account": "खाते तयार करा", "Find my possible benefits": "माझे संभाव्य लाभ शोधा", "How it works": "हे कसे कार्य करते", "Explore schemes": "योजना पहा", "Benefit navigator": "लाभ मार्गदर्शक", "Myself": "माझ्यासाठी", "For Someone Else": "दुसऱ्या व्यक्तीसाठी", "Situation": "परिस्थिती", "Documents": "कागदपत्रे", "Continue": "पुढे जा", "Previous": "मागील", "Building your plan": "तुमची योजना तयार होत आहे", "Your situation": "तुमची परिस्थिती", "Their situation": "त्यांची परिस्थिती", "Documents you have": "तुमच्याकडील कागदपत्रे", "Answer what you know.": "तुम्हाला माहीत असलेली माहिती द्या." },
  bn: { "Choose language": "ভাষা বেছে নিন", "Open workspace": "ওয়ার্কস্পেস খুলুন", "Profile settings": "প্রোফাইল সেটিংস", "Profile": "প্রোফাইল", "Log out": "লগ আউট", "Log in": "লগ ইন", "Create account": "অ্যাকাউন্ট তৈরি করুন", "Find my possible benefits": "আমার সম্ভাব্য সুবিধা খুঁজুন", "How it works": "এটি কীভাবে কাজ করে", "Explore schemes": "স্কিম দেখুন", "Benefit navigator": "সুবিধা নেভিগেটর", "Myself": "আমার জন্য", "For Someone Else": "অন্য কারও জন্য", "Situation": "পরিস্থিতি", "Documents": "নথি", "Continue": "চালিয়ে যান", "Previous": "পূর্ববর্তী", "Building your plan": "আপনার পরিকল্পনা তৈরি হচ্ছে", "Your situation": "আপনার পরিস্থিতি", "Their situation": "তাঁর পরিস্থিতি", "Documents you have": "আপনার কাছে থাকা নথি", "Answer what you know.": "আপনি যা জানেন তা জানান।" },
  te: { "Choose language": "భాషను ఎంచుకోండి", "Open workspace": "వర్క్‌స్పేస్ తెరవండి", "Profile settings": "ప్రొఫైల్ సెట్టింగ్‌లు", "Profile": "ప్రొఫైల్", "Log out": "లాగ్ అవుట్", "Log in": "లాగ్ ఇన్", "Create account": "ఖాతాను సృష్టించండి", "Find my possible benefits": "నా సాధ్యమైన ప్రయోజనాలను కనుగొనండి", "How it works": "ఇది ఎలా పనిచేస్తుంది", "Explore schemes": "పథకాలను చూడండి", "Benefit navigator": "ప్రయోజన మార్గదర్శి", "Myself": "నాకోసం", "For Someone Else": "మరొకరి కోసం", "Situation": "పరిస్థితి", "Documents": "పత్రాలు", "Continue": "కొనసాగించండి", "Previous": "మునుపటిది", "Building your plan": "మీ ప్రణాళిక సిద్ధమవుతోంది", "Your situation": "మీ పరిస్థితి", "Their situation": "వారి పరిస్థితి", "Documents you have": "మీ వద్ద ఉన్న పత్రాలు", "Answer what you know.": "మీకు తెలిసినదాన్ని తెలియజేయండి." },
  ta: { "Choose language": "மொழியைத் தேர்ந்தெடுக்கவும்", "Open workspace": "பணியிடத்தைத் திறக்கவும்", "Profile settings": "சுயவிவர அமைப்புகள்", "Profile": "சுயவிவரம்", "Log out": "வெளியேறு", "Log in": "உள்நுழையவும்", "Create account": "கணக்கை உருவாக்கவும்", "Find my possible benefits": "எனது சாத்தியமான பலன்களைக் கண்டறியவும்", "How it works": "இது எப்படி செயல்படுகிறது", "Explore schemes": "திட்டங்களைப் பார்க்கவும்", "Benefit navigator": "பலன் வழிகாட்டி", "Myself": "எனக்காக", "For Someone Else": "வேறொருவருக்காக", "Situation": "நிலைமை", "Documents": "ஆவணங்கள்", "Continue": "தொடரவும்", "Previous": "முந்தையது", "Building your plan": "உங்கள் திட்டம் தயாராகிறது", "Your situation": "உங்கள் நிலைமை", "Their situation": "அவர்களின் நிலைமை", "Documents you have": "உங்களிடம் உள்ள ஆவணங்கள்", "Answer what you know.": "உங்களுக்குத் தெரிந்ததைச் சொல்லுங்கள்." },
  gu: { "Choose language": "ભાષા પસંદ કરો", "Open workspace": "વર્કસ્પેસ ખોલો", "Profile settings": "પ્રોફાઇલ સેટિંગ્સ", "Profile": "પ્રોફાઇલ", "Log out": "લૉગ આઉટ", "Log in": "લૉગ ઇન", "Create account": "એકાઉન્ટ બનાવો", "Find my possible benefits": "મારા સંભવિત લાભો શોધો", "How it works": "આ કેવી રીતે કામ કરે છે", "Explore schemes": "યોજનાઓ જુઓ", "Benefit navigator": "લાભ માર્ગદર્શક", "Myself": "મારા માટે", "For Someone Else": "બીજા કોઈ માટે", "Situation": "પરિસ્થિતિ", "Documents": "દસ્તાવેજો", "Continue": "ચાલુ રાખો", "Previous": "પહેલાનું", "Building your plan": "તમારી યોજના તૈયાર થઈ રહી છે", "Your situation": "તમારી પરિસ્થિતિ", "Their situation": "તેમની પરિસ્થિતિ", "Documents you have": "તમારી પાસેના દસ્તાવેજો", "Answer what you know.": "તમને જે ખબર હોય તે જણાવો." },
  kn: { "Choose language": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ", "Open workspace": "ಕಾರ್ಯಸ್ಥಳ ತೆರೆಯಿರಿ", "Profile settings": "ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು", "Profile": "ಪ್ರೊಫೈಲ್", "Log out": "ಲಾಗ್ ಔಟ್", "Log in": "ಲಾಗ್ ಇನ್", "Create account": "ಖಾತೆ ರಚಿಸಿ", "Find my possible benefits": "ನನ್ನ ಸಾಧ್ಯ ಪ್ರಯೋಜನಗಳನ್ನು ಹುಡುಕಿ", "How it works": "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ", "Explore schemes": "ಯೋಜನೆಗಳನ್ನು ನೋಡಿ", "Benefit navigator": "ಪ್ರಯೋಜನ ಮಾರ್ಗದರ್ಶಿ", "Myself": "ನನಗಾಗಿ", "For Someone Else": "ಬೇರೆಯವರಿಗಾಗಿ", "Situation": "ಪರಿಸ್ಥಿತಿ", "Documents": "ದಾಖಲೆಗಳು", "Continue": "ಮುಂದುವರಿಸಿ", "Previous": "ಹಿಂದಿನದು", "Building your plan": "ನಿಮ್ಮ ಯೋಜನೆ ಸಿದ್ಧವಾಗುತ್ತಿದೆ", "Your situation": "ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿ", "Their situation": "ಅವರ ಪರಿಸ್ಥಿತಿ", "Documents you have": "ನಿಮ್ಮಲ್ಲಿರುವ ದಾಖಲೆಗಳು", "Answer what you know.": "ನಿಮಗೆ ತಿಳಿದಿರುವುದನ್ನು ತಿಳಿಸಿ." },
  ml: { "Choose language": "ഭാഷ തിരഞ്ഞെടുക്കുക", "Open workspace": "വർക്ക്സ്പേസ് തുറക്കുക", "Profile settings": "പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ", "Profile": "പ്രൊഫൈൽ", "Log out": "ലോഗ് ഔട്ട്", "Log in": "ലോഗ് ഇൻ", "Create account": "അക്കൗണ്ട് സൃഷ്ടിക്കുക", "Find my possible benefits": "എന്റെ സാധ്യതയുള്ള ആനുകൂല്യങ്ങൾ കണ്ടെത്തുക", "How it works": "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു", "Explore schemes": "പദ്ധതികൾ കാണുക", "Benefit navigator": "ആനുകൂല്യ മാർഗ്ഗദർശി", "Myself": "എനിക്കായി", "For Someone Else": "മറ്റൊരാൾക്കായി", "Situation": "സാഹചര്യം", "Documents": "രേഖകൾ", "Continue": "തുടരുക", "Previous": "മുമ്പത്തേത്", "Building your plan": "നിങ്ങളുടെ പദ്ധതി തയ്യാറാകുന്നു", "Your situation": "നിങ്ങളുടെ സാഹചര്യം", "Their situation": "അവരുടെ സാഹചര്യം", "Documents you have": "നിങ്ങളുടെ പക്കലുള്ള രേഖകൾ", "Answer what you know.": "നിങ്ങൾക്കറിയാവുന്നത് പറയുക." },
  pa: { "Choose language": "ਭਾਸ਼ਾ ਚੁਣੋ", "Open workspace": "ਵਰਕਸਪੇਸ ਖੋਲ੍ਹੋ", "Profile settings": "ਪ੍ਰੋਫਾਈਲ ਸੈਟਿੰਗਾਂ", "Profile": "ਪ੍ਰੋਫਾਈਲ", "Log out": "ਲਾਗ ਆਉਟ", "Log in": "ਲਾਗ ਇਨ", "Create account": "ਖਾਤਾ ਬਣਾਓ", "Find my possible benefits": "ਮੇਰੇ ਸੰਭਾਵਿਤ ਲਾਭ ਲੱਭੋ", "How it works": "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ", "Explore schemes": "ਯੋਜਨਾਵਾਂ ਦੇਖੋ", "Benefit navigator": "ਲਾਭ ਮਾਰਗਦਰਸ਼ਕ", "Myself": "ਮੇਰੇ ਲਈ", "For Someone Else": "ਕਿਸੇ ਹੋਰ ਲਈ", "Situation": "ਸਥਿਤੀ", "Documents": "ਦਸਤਾਵੇਜ਼", "Continue": "ਜਾਰੀ ਰੱਖੋ", "Previous": "ਪਿਛਲਾ", "Building your plan": "ਤੁਹਾਡੀ ਯੋਜਨਾ ਤਿਆਰ ਹੋ ਰਹੀ ਹੈ", "Your situation": "ਤੁਹਾਡੀ ਸਥਿਤੀ", "Their situation": "ਉਹਨਾਂ ਦੀ ਸਥਿਤੀ", "Documents you have": "ਤੁਹਾਡੇ ਕੋਲ ਦਸਤਾਵੇਜ਼", "Answer what you know.": "ਜੋ ਤੁਹਾਨੂੰ ਪਤਾ ਹੈ ਉਹ ਦੱਸੋ।" },
  or: { "Choose language": "ଭାଷା ବାଛନ୍ତୁ", "Open workspace": "ୱର୍କସ୍ପେସ ଖୋଲନ୍ତୁ", "Profile settings": "ପ୍ରୋଫାଇଲ୍ ସେଟିଂସ୍", "Profile": "ପ୍ରୋଫାଇଲ୍", "Log out": "ଲଗ୍ ଆଉଟ୍", "Log in": "ଲଗ୍ ଇନ୍", "Create account": "ଆକାଉଣ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ", "Find my possible benefits": "ମୋର ସମ୍ଭାବ୍ୟ ଲାଭ ଖୋଜନ୍ତୁ", "How it works": "ଏହା କିପରି କାମ କରେ", "Explore schemes": "ଯୋଜନା ଦେଖନ୍ତୁ", "Benefit navigator": "ଲାଭ ମାର୍ଗଦର୍ଶକ", "Myself": "ମୋ ପାଇଁ", "For Someone Else": "ଅନ୍ୟ କାହା ପାଇଁ", "Situation": "ପରିସ୍ଥିତି", "Documents": "ଦଲିଲ", "Continue": "ଜାରି ରଖନ୍ତୁ", "Previous": "ପୂର୍ବବର୍ତ୍ତୀ", "Building your plan": "ଆପଣଙ୍କ ଯୋଜନା ପ୍ରସ୍ତୁତ ହେଉଛି", "Your situation": "ଆପଣଙ୍କ ପରିସ୍ଥିତି", "Their situation": "ସେମାନଙ୍କ ପରିସ୍ଥିତି", "Documents you have": "ଆପଣଙ୍କ ପାଖରେ ଥିବା ଦଲିଲ", "Answer what you know.": "ଆପଣ ଯାହା ଜାଣନ୍ତି ତାହା କୁହନ୍ତୁ।" },
  as: { "Choose language": "ভাষা বাছনি কৰক", "Open workspace": "ৱৰ্কস্পেচ খোলক", "Profile settings": "প্ৰফাইল ছেটিংছ", "Profile": "প্ৰফাইল", "Log out": "লগ আউট", "Log in": "লগ ইন", "Create account": "একাউণ্ট তৈয়াৰ কৰক", "Find my possible benefits": "মোৰ সম্ভাৱ্য লাভ বিচাৰক", "How it works": "ই কেনেকৈ কাম কৰে", "Explore schemes": "আঁচনি চাওক", "Benefit navigator": "লাভ নেভিগেটৰ", "Myself": "মোৰ বাবে", "For Someone Else": "আন কাৰোবাৰ বাবে", "Situation": "পৰিস্থিতি", "Documents": "নথিপত্ৰ", "Continue": "আগবাঢ়ক", "Previous": "পূৰ্বৱৰ্তী", "Building your plan": "আপোনাৰ পৰিকল্পনা প্ৰস্তুত হৈছে", "Your situation": "আপোনাৰ পৰিস্থিতি", "Their situation": "তেওঁলোকৰ পৰিস্থিতি", "Documents you have": "আপোনাৰ হাতত থকা নথিপত্ৰ", "Answer what you know.": "আপুনি যি জানে তাক জনাওক।" }
};

// Shared Nagarik interface vocabulary. It complements the longer, page-specific
// phrases above so labels stay localized wherever they are reused.
const languageOrder = ["hi", "mr", "bn", "te", "ta", "gu", "kn", "ml", "pa", "or", "as"] as const;
const termRows: Record<string, string[]> = {
  "Full name": ["पूरा नाम", "पूर्ण नाव", "পুরো নাম", "పూర్తి పేరు", "முழுப் பெயர்", "પૂરું નામ", "ಪೂರ್ಣ ಹೆಸರು", "പൂർണ്ണ പേര്", "ਪੂਰਾ ਨਾਮ", "ପୂରା ନାମ", "সম্পূৰ্ণ নাম"],
  "Age": ["आयु", "वय", "বয়স", "వయస్సు", "வயது", "ઉંમર", "ವಯಸ್ಸು", "പ്രായം", "ਉਮਰ", "ବୟସ", "বয়স"],
  "Gender": ["लिंग", "लिंग", "লিঙ্গ", "లింగం", "பாலினம்", "લિંગ", "ಲಿಂಗ", "ലിംഗം", "ਲਿੰਗ", "ଲିଙ୍ଗ", "লিংগ"],
  "State": ["राज्य", "राज्य", "রাজ্য", "రాష్ట్రం", "மாநிலம்", "રાજ્ય", "ರಾಜ್ಯ", "സംസ്ഥാനം", "ਰਾਜ", "ରାଜ୍ୟ", "ৰাজ্য"],
  "District": ["जिला", "जिल्हा", "জেলা", "జిల్లా", "மாவட்டம்", "જિલ્લો", "ಜಿಲ್ಲೆ", "ജില്ല", "ਜ਼ਿਲ੍ਹਾ", "ଜିଲ୍ଲା", "জিলা"],
  "Email": ["ईमेल", "ईमेल", "ইমেল", "ఇమెయిల్", "மின்னஞ்சல்", "ઇમેઇલ", "ಇಮೇಲ್", "ഇമെയിൽ", "ਈਮੇਲ", "ଇମେଲ୍", "ইমেইল"],
  "Password": ["पासवर्ड", "पासवर्ड", "পাসওয়ার্ড", "పాస్‌వర్డ్", "கடவுச்சொல்", "પાસવર્ડ", "ಪಾಸ್‌ವರ್ಡ್", "പാസ്‌വേഡ്", "ਪਾਸਵਰਡ", "ପାସୱାର୍ଡ", "পাছৱৰ্ড"],
  "Social category": ["सामाजिक श्रेणी", "सामाजिक प्रवर्ग", "সামাজিক বিভাগ", "సామాజిక వర్గం", "சமூகப் பிரிவு", "સામાજિક વર્ગ", "ಸಾಮಾಜಿಕ ವರ್ಗ", "സാമൂഹിക വിഭാഗം", "ਸਮਾਜਿਕ ਸ਼੍ਰੇਣੀ", "ସାମାଜିକ ବର୍ଗ", "সামাজিক শ্ৰেণী"],
  "Employment status": ["रोजगार स्थिति", "रोजगाराची स्थिती", "কর্মসংস্থানের অবস্থা", "ఉపాధి స్థితి", "வேலை நிலை", "રોજગાર સ્થિતિ", "ಉದ್ಯೋಗ ಸ್ಥಿತಿ", "തൊഴിൽ നില", "ਰੁਜ਼ਗਾਰ ਸਥਿਤੀ", "ରୋଜଗାର ସ୍ଥିତି", "নিয়োগৰ স্থিতি"],
  "Occupation": ["व्यवसाय", "व्यवसाय", "পেশা", "వృత్తి", "தொழில்", "વ્યવસાય", "ವೃತ್ತಿ", "തൊഴിൽ", "ਪੇਸ਼ਾ", "ବୃତ୍ତି", "পেছা"],
  "Housing": ["आवास", "निवास", "বাসস্থান", "నివాసం", "வீட்டு நிலை", "રહેઠાણ", "ವಸತಿ", "താമസം", "ਰਿਹਾਇਸ਼", "ବାସସ୍ଥାନ", "বাসস্থান"],
  "Marital status": ["वैवाहिक स्थिति", "वैवाहिक स्थिती", "বৈবাহিক অবস্থা", "వైవాహిక స్థితి", "திருமண நிலை", "વૈવાહિક સ્થિતિ", "ವೈವಾಹಿಕ ಸ್ಥಿತಿ", "വൈവാഹിക സ്ഥിതി", "ਵਿਆਹੁਤਾ ਸਥਿਤੀ", "ବୈବାହିକ ସ୍ଥିତି", "বৈবাহিক স্থিতি"],
  "Possible matches": ["संभावित मिलान", "संभाव्य जुळण्या", "সম্ভাব্য মিল", "సంభావ్య సరిపోలికలు", "சாத்தியமான பொருத்தங்கள்", "સંભવિત મેળ", "ಸಂಭಾವ್ಯ ಹೊಂದಾಣಿಕೆಗಳು", "സാധ്യമായ പൊരുത്തങ്ങൾ", "ਸੰਭਾਵਿਤ ਮੇਲ", "ସମ୍ଭାବ୍ୟ ମେଳ", "সম্ভাৱ্য মিল"],
  "Bundle value": ["पैकेज मूल्य", "लाभ संच मूल्य", "প্যাকেজ মূল্য", "ప్యాకేజీ విలువ", "தொகுப்பு மதிப்பு", "પેકેજ મૂલ્ય", "ಪ್ಯಾಕೇಜ್ ಮೌಲ್ಯ", "പാക്കേജ് മൂല്യം", "ਪੈਕੇਜ ਮੁੱਲ", "ପ୍ୟାକେଜ ମୂଲ୍ୟ", "পেকেজ মূল্য"],
  "Documents to find": ["ढूंढने के दस्तावेज़", "शोधायची कागदपत्रे", "খুঁজে পাওয়ার নথি", "కనుగొనాల్సిన పత్రాలు", "கண்டறிய வேண்டிய ஆவணங்கள்", "શોધવાના દસ્તાવેજો", "ಹುಡುಕಬೇಕಾದ ದಾಖಲೆಗಳು", "കണ്ടെത്തേണ്ട രേഖകൾ", "ਲੱਭਣ ਲਈ ਦਸਤਾਵੇਜ਼", "ଖୋଜିବାକୁ ଥିବା ଦଲିଲ", "বিচাৰিবলগীয়া নথি"],
  "Amount not listed": ["राशि सूचीबद्ध नहीं है", "रक्कम नमूद नाही", "পরিমাণ তালিকাভুক্ত নয়", "మొత్తం జాబితా చేయబడలేదు", "தொகை பட்டியலிடப்படவில்லை", "રકમ સૂચિબદ્ધ નથી", "ಮೊತ್ತವನ್ನು ಪಟ್ಟಿ ಮಾಡಿಲ್ಲ", "തുക പട്ടികപ്പെടുത്തിയിട്ടില്ല", "ਰਕਮ ਸੂਚੀਬੱਧ ਨਹੀਂ", "ରାଶି ତାଲିକାଭୁକ୍ତ ନୁହେଁ", "পৰিমাণ তালিকাভুক্ত নহয়"],
  "Profile match": ["प्रोफ़ाइल मिलान", "प्रोफाइल जुळणी", "প্রোফাইল মিল", "ప్రొఫైల్ సరిపోలిక", "சுயவிவர பொருத்தம்", "પ્રોફાઇલ મેળ", "ಪ್ರೊಫೈಲ್ ಹೊಂದಾಣಿಕೆ", "പ്രൊഫൈൽ പൊരുത്തം", "ਪ੍ਰੋਫਾਈਲ ਮੇਲ", "ପ୍ରୋଫାଇଲ୍ ମେଳ", "প্ৰফাইল মিল"],
  "Check conditions": ["शर्तें जांचें", "अटी तपासा", "শর্ত যাচাই করুন", "నిబంధనలు తనిఖీ చేయండి", "நிபந்தனைகளைச் சரிபார்க்கவும்", "શરતો તપાસો", "ಷರತ್ತುಗಳನ್ನು ಪರಿಶೀಲಿಸಿ", "നിബന്ധനകൾ പരിശോധിക്കുക", "ਸ਼ਰਤਾਂ ਦੀ ਜਾਂਚ ਕਰੋ", "ସର୍ତ୍ତ ଯାଞ୍ଚ କରନ୍ତୁ", "চৰ্ত পৰীক্ষা কৰক"],
  "View details & apply": ["विवरण देखें और आवेदन करें", "तपशील पहा आणि अर्ज करा", "বিবরণ দেখুন ও আবেদন করুন", "వివరాలు చూడండి మరియు దరఖాస్తు చేయండి", "விவரங்களைப் பார்த்து விண்ணப்பிக்கவும்", "વિગતો જુઓ અને અરજી કરો", "ವಿವರಗಳನ್ನು ನೋಡಿ ಮತ್ತು ಅರ್ಜಿ ಸಲ್ಲಿಸಿ", "വിശദാംശങ്ങൾ കണ്ട് അപേക്ഷിക്കുക", "ਵੇਰਵੇ ਦੇਖੋ ਅਤੇ ਅਰਜ਼ੀ ਦਿਓ", "ବିବରଣୀ ଦେଖନ୍ତୁ ଏବଂ ଆବେଦନ କରନ୍ତୁ", "বিৱৰণ চাওক আৰু আবেদন কৰক"],
};
for (const [source, translations] of Object.entries(termRows)) {
  languageOrder.forEach((language, index) => { nagarikMessages[language][source] = translations[index]; });
}

Object.assign(nagarikMessages.hi, {
  "A clearer route to public support": "सार्वजनिक सहायता का एक स्पष्ट रास्ता",
  "Know what": "जानें कि",
  "comes next.": "आगे क्या है।",
  "Nagarik turns a complicated benefits search into a simple, explainable plan — what may fit, what cannot be combined, and which document to find first.": "नागरिक जटिल लाभ खोज को एक सरल, स्पष्ट योजना में बदलता है — क्या उपयुक्त हो सकता है, क्या साथ नहीं लिया जा सकता और कौन-सा दस्तावेज़ पहले ढूंढना है।",
  "Takes about 2 minutes": "लगभग 2 मिनट लगते हैं",
  "Your support map": "आपका सहायता मानचित्र",
  "A plan that": "एक योजना जो",
  "makes sense.": "समझ में आए।",
  "Find schemes that fit your situation": "अपनी स्थिति के अनुकूल योजनाएं खोजें",
  "See compatible combinations": "संगत संयोजन देखें",
  "Get a document-first checklist": "दस्तावेज़-प्रथम चेकलिस्ट पाएं",
  "Connecting to service…": "सेवा से जुड़ रहा है…",
  "Service ready for a demo check": "सेवा डेमो जांच के लिए तैयार है",
  "The Nagarik way": "नागरिक का तरीका",
  "Less guesswork.": "कम अनुमान।",
  "More confidence.": "ज्यादा भरोसा।",
  "We show the reasoning behind every result so you can decide what to do with it.": "हम हर परिणाम का कारण दिखाते हैं ताकि आप तय कर सकें कि आगे क्या करना है।",
  "Tell us about you": "अपने बारे में बताएं",
  "A few practical details. No account or paperwork upload required.": "कुछ व्यावहारिक जानकारी। खाता या दस्तावेज़ अपलोड की आवश्यकता नहीं।",
  "We compare the rules": "हम नियमों की तुलना करते हैं",
  "Eligibility, overlaps, missing information and documents — together.": "पात्रता, ओवरलैप, अनुपलब्ध जानकारी और दस्तावेज़ — एक साथ।",
  "Take the next step": "अगला कदम उठाएं",
  "A ranked bundle and a local-office-ready checklist.": "प्राथमिकता वाला लाभ-संच और स्थानीय कार्यालय के लिए तैयार चेकलिस्ट।",
  "Inside the navigator": "नेविगेटर के अंदर",
  "Built around real decisions.": "वास्तविक निर्णयों के लिए बनाया गया।",
  "Explore sourced government schemes with eligibility, benefits, and application requirements.": "पात्रता, लाभ और आवेदन आवश्यकताओं वाली विश्वसनीय सरकारी योजनाएं देखें।",
  "Want a personalised answer?": "व्यक्तिगत उत्तर चाहिए?",
  "Create your profile once, then continue with your situation.": "अपनी प्रोफ़ाइल एक बार बनाएं, फिर अपनी स्थिति के साथ आगे बढ़ें।",
  "Create my account": "मेरा खाता बनाएं",
  "Built with clarity": "स्पष्टता के साथ बनाया गया",
  "Results explain possible matches, scheme conflicts, and document requirements in plain language.": "परिणाम संभावित मेल, योजना टकराव और दस्तावेज़ आवश्यकताओं को सरल भाषा में समझाते हैं।",
  "A clearer, calmer way to understand possible public benefits and prepare for the next step.": "संभावित सार्वजनिक लाभों को समझने और अगले कदम की तैयारी का एक स्पष्ट, सहज तरीका।",
  "Public support, made easier to understand.": "सार्वजनिक सहायता, समझने में आसान।"
});
