import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronDown, ChevronUp, CircleAlert, CircleCheck, Scale, X } from 'lucide-react';
import { Link } from 'wouter';
import type { AnalysisResult, Checklist, Scheme } from '@workspace/api-client-react';
import { useGetChecklist, useGetScheme } from '@workspace/api-client-react';
import { BrandMark } from '@/components/BrandMark';
import { DemoDisclaimer, EmptyState, ErrorPanel, LoadingLines, SchemeIcon, SectionKicker, SuccessTick } from '@/components/Primitives';

function money(value: number) {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value);
}

function SchemeRow({ scheme, recommendation, reason, onDetails }: { scheme: Scheme; recommendation?: string; reason?: string; onDetails: () => void }) {
  return <div className="flex flex-col gap-4 rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4 sm:flex-row sm:items-center" data-testid={`row-result-scheme-${scheme.id}`}><SchemeIcon category={scheme.category} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-xl font-bold">{scheme.name}</h3><span className="rounded-full bg-[hsl(var(--secondary))] px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-[hsl(var(--primary))]">{scheme.category}</span></div><p className="mt-1 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{reason || scheme.benefit}</p></div><div className="flex items-center gap-3 sm:flex-col sm:items-end"><span className="text-sm font-bold text-[hsl(var(--primary))]">{scheme.benefitValue ? money(scheme.benefitValue) : scheme.benefit}</span><button type="button" onClick={onDetails} className="text-xs font-bold text-[hsl(var(--muted-foreground))] underline-offset-4 hover:text-[hsl(var(--primary))] hover:underline" data-testid={`button-details-${scheme.id}`}>View rules</button>{recommendation && <span className="text-[11px] font-semibold text-[hsl(var(--accent-foreground))]">{recommendation}</span>}</div></div>;
}

function ChecklistCard({ checklist }: { checklist: Checklist }) {
  const [open, setOpen] = useState(true);
  const completed = checklist.items.filter((item) => item.completed).length;
  return <section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))]" data-testid="section-checklist"><button type="button" onClick={() => setOpen(!open)} className="flex w-full items-center justify-between gap-4 p-5 text-left" data-testid="button-toggle-checklist"><div><SectionKicker>Ready to move</SectionKicker><h2 className="font-display text-2xl font-bold">Your application checklist</h2><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{completed} of {checklist.items.length} preparation steps complete</p></div>{open ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</button>{open && <div className="space-y-3 border-t border-[hsl(var(--border))] p-5">{checklist.items.map((item) => <div key={item.id} className="flex gap-3 rounded-xl bg-[hsl(var(--background))] p-3.5" data-testid={`checklist-item-${item.id}`}><span className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded-full ${item.completed ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'border border-[hsl(var(--input))]'}`}>{item.completed && <Check size={13} strokeWidth={3} />}</span><div><p className="text-sm font-semibold">{item.label}</p><p className="mt-1 text-xs leading-relaxed text-[hsl(var(--muted-foreground))]">{item.detail}</p></div></div>)}</div>}</section>;
}

export default function ResultsPage() {
  const [analysis] = useState<AnalysisResult | null>(() => {
    try { return JSON.parse(sessionStorage.getItem('jansahay-analysis') || 'null') as AnalysisResult | null; } catch { return null; }
  });
  const [detailSchemeId, setDetailSchemeId] = useState<string | null>(null);
  const citizenId = analysis?.citizenId ?? '';
  const checklistQuery = useGetChecklist(citizenId, { query: { enabled: Boolean(citizenId), queryKey: [`/api/checklist/${citizenId}`] } });
  const schemeQuery = useGetScheme(detailSchemeId ?? '', { query: { enabled: Boolean(detailSchemeId), queryKey: [`/api/schemes/${detailSchemeId ?? ''}`] } });
  const schemesById = useMemo(() => new Map((analysis?.eligibleSchemes ?? []).concat(analysis?.ineligibleSchemes ?? [], analysis?.missingInformationSchemes ?? []).map((scheme) => [scheme.id, scheme])), [analysis]);

  if (!analysis) return <div className="min-h-[100dvh] bg-[hsl(var(--background))]"><header className="border-b border-[hsl(var(--border))] bg-[hsl(var(--card))]"><div className="mx-auto max-w-7xl px-5 py-4 lg:px-10"><Link href="/" data-testid="link-results-home"><BrandMark /></Link></div></header><main className="mx-auto max-w-xl px-5 py-20"><EmptyState title="Your analysis is not open" detail="Start a profile check first. Your results will appear here at the end." /><Link href="/app" className="mx-auto mt-6 flex w-fit items-center gap-2 rounded-full bg-[hsl(var(--primary))] px-5 py-3 text-sm font-bold text-[hsl(var(--primary-foreground))]" data-testid="link-start-results">Start a check <ArrowRight size={16} /></Link></main></div>;

  const displayedChecklist = checklistQuery.data ?? analysis.checklist;
  const selected = analysis.optimization.selectedSchemes.map((entry) => ({ ...entry, scheme: schemesById.get(entry.schemeId) })).filter((entry): entry is typeof entry & { scheme: Scheme } => Boolean(entry.scheme));
  const missingDocuments = displayedChecklist.missingDocuments;
  return <div className="grain min-h-[100dvh] bg-[hsl(var(--background))]">
    <header className="border-b border-[hsl(var(--border))] bg-[hsl(var(--card)/.85)]"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-10"><Link href="/" data-testid="link-results-logo"><BrandMark /></Link><Link href="/app" className="inline-flex items-center gap-2 text-sm font-semibold text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--primary))]" data-testid="link-new-check"><ArrowLeft size={16} /> New check</Link></div></header>
    <main className="mx-auto max-w-7xl px-5 py-9 lg:px-10 lg:py-14">
      <div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><SectionKicker>Analysis complete</SectionKicker><h1 className="font-display text-4xl font-bold tracking-[-.05em] sm:text-6xl">A clearer path<br /><span className="text-[hsl(var(--primary))]">starts here.</span></h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{analysis.analysisSummary[0] || 'Here is what your profile may qualify for, what to prepare, and how the options fit together.'}</p></div><DemoDisclaimer compact /></div>
      <div className="mt-9 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[hsl(var(--primary))] p-5 text-[hsl(var(--primary-foreground))]" data-testid="stat-eligible"><p className="text-xs font-bold uppercase tracking-wider text-[hsl(var(--accent))]">Possible matches</p><p className="mt-3 font-display text-4xl font-bold">{analysis.eligibleSchemes.length}</p><p className="mt-1 text-xs text-[hsl(var(--primary-foreground)/.68)]">schemes fit the profile</p></div><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5" data-testid="stat-bundle-value"><p className="text-xs font-bold uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Bundle value</p><p className="mt-3 font-display text-4xl font-bold text-[hsl(var(--primary))]">{money(analysis.optimization.totalBenefitValue)}</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">estimated combined support</p></div><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5" data-testid="stat-documents"><p className="text-xs font-bold uppercase tracking-wider text-[hsl(var(--muted-foreground))]">Documents to find</p><p className="mt-3 font-display text-4xl font-bold">{missingDocuments.length}</p><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">before you apply</p></div></div>
      <div className="mt-10 grid gap-8 lg:grid-cols-[1.3fr_.7fr]">
        <div className="space-y-8">
          <section data-testid="section-optimized-bundle"><div className="mb-4 flex items-end justify-between gap-4"><div><SectionKicker>Recommended together</SectionKicker><h2 className="font-display text-3xl font-bold">Your best-fit bundle</h2></div><span className="hidden rounded-full bg-[hsl(var(--secondary))] px-3 py-1.5 text-xs font-bold text-[hsl(var(--primary))] sm:block">Score {analysis.optimization.score}/100</span></div><div className="space-y-3">{selected.length ? selected.map((entry) => <SchemeRow key={entry.schemeId} scheme={entry.scheme} recommendation={entry.recommendation} reason={entry.reason} onDetails={() => setDetailSchemeId(entry.schemeId)} />) : <EmptyState title="No bundle found yet" detail="The analysis could not assemble a compatible set. Review alternatives below or begin a new check." />}</div></section>
          <section data-testid="section-eligibility"><div className="mb-4"><SectionKicker>What the rules say</SectionKicker><h2 className="font-display text-3xl font-bold">Eligibility, in plain language</h2></div><div className="space-y-3">{analysis.eligibleSchemes.map((scheme) => <div key={scheme.id} className="flex gap-3 rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4"><CircleCheck className="mt-0.5 shrink-0 text-[hsl(var(--primary))]" size={19} /><div><p className="font-semibold">{scheme.name}</p><p className="mt-1 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{analysis.eligibility.find((item) => item.schemeId === scheme.id)?.reasons.join(' ') || 'Your profile meets the main criteria in this prototype.'}</p></div></div>)}{analysis.missingInformationSchemes.map((scheme) => <div key={scheme.id} className="flex gap-3 rounded-2xl border border-[hsl(var(--accent)/.45)] bg-[hsl(var(--accent)/.08)] p-4"><CircleAlert className="mt-0.5 shrink-0 text-[hsl(var(--accent-foreground))]" size={19} /><div><p className="font-semibold">{scheme.name}</p><p className="mt-1 text-sm leading-relaxed text-[hsl(var(--muted-foreground))]">{analysis.eligibility.find((item) => item.schemeId === scheme.id)?.missingInformation.join(' ') || 'A little more information is needed before this can be confirmed.'}</p></div></div>)}</div></section>
          <ChecklistCard checklist={displayedChecklist} />
        </div>
        <aside className="space-y-5">
          <section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5" data-testid="section-next-actions"><SectionKicker>Do this first</SectionKicker><h2 className="font-display text-2xl font-bold">Your next three moves</h2><div className="mt-5 space-y-4"><SuccessTick>Gather the {missingDocuments.length || 'required'} missing document{missingDocuments.length === 1 ? '' : 's'}.</SuccessTick><SuccessTick>Ask your local office to confirm current scheme rules.</SuccessTick><SuccessTick>Apply to the highest-priority scheme first.</SuccessTick></div><Link href="/app" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full border border-[hsl(var(--primary))] px-4 py-2.5 text-sm font-bold text-[hsl(var(--primary))] transition-colors hover:bg-[hsl(var(--secondary))]" data-testid="link-run-another">Run another profile <ArrowRight size={15} /></Link></section>
          <section className="rounded-2xl bg-[hsl(var(--primary))] p-5 text-[hsl(var(--primary-foreground))]" data-testid="section-conflicts"><div className="flex items-center gap-2 text-[hsl(var(--accent))]"><Scale size={18} /><span className="text-xs font-bold uppercase tracking-wider">Compatibility</span></div><h2 className="mt-4 font-display text-2xl font-bold">{analysis.conflicts.length ? 'A couple of overlaps to know' : 'Your bundle is compatible'}</h2>{analysis.conflicts.length ? <div className="mt-4 space-y-3">{analysis.conflicts.map((conflict, index) => <div key={`${conflict.schemeAId}-${conflict.schemeBId}-${index}`} className="rounded-xl border border-[hsl(var(--primary-foreground)/.13)] bg-[hsl(var(--primary-foreground)/.06)] p-3 text-xs leading-relaxed text-[hsl(var(--primary-foreground)/.78)]">{schemesById.get(conflict.schemeAId)?.name || conflict.schemeAId} and {schemesById.get(conflict.schemeBId)?.name || conflict.schemeBId}: {conflict.reason}</div>)}</div> : <p className="mt-3 text-sm leading-relaxed text-[hsl(var(--primary-foreground)/.7)]">The recommended schemes can be pursued together according to the prototype rules.</p>}</section>
          {analysis.optimization.alternatives.length > 0 && <section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5" data-testid="section-alternatives"><SectionKicker>Other routes</SectionKicker><h2 className="font-display text-2xl font-bold">Worth knowing</h2><div className="mt-4 space-y-3">{analysis.optimization.alternatives.slice(0, 2).map((alternative, index) => <div key={`${alternative.name}-${index}`} className="rounded-xl bg-[hsl(var(--background))] p-3"><div className="flex items-center justify-between gap-3 text-sm font-semibold"><span>{alternative.name}</span><span className="text-xs text-[hsl(var(--primary))]">{alternative.coverage}% coverage</span></div><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Compatibility {alternative.compatibility}% · document readiness {alternative.documentReadiness}%</p></div>)}</div></section>}
        </aside>
      </div>
    </main>
    {detailSchemeId && <div className="fixed inset-0 z-40 flex items-end justify-center bg-[hsl(var(--foreground)/.35)] p-0 sm:items-center sm:p-6" role="dialog" aria-modal="true" data-testid="dialog-scheme-details"><div className="max-h-[88vh] w-full max-w-xl overflow-auto rounded-t-3xl bg-[hsl(var(--card))] p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-start justify-between"><div><SectionKicker>Scheme detail</SectionKicker><h2 className="font-display text-3xl font-bold">{schemeQuery.data?.name || schemesById.get(detailSchemeId)?.name}</h2></div><button type="button" onClick={() => setDetailSchemeId(null)} className="grid size-9 place-items-center rounded-full bg-[hsl(var(--muted))]" data-testid="button-close-details"><X size={17} /></button></div>{schemeQuery.isLoading ? <div className="mt-6"><LoadingLines count={4} /></div> : schemeQuery.isError ? <div className="mt-6"><ErrorPanel /></div> : schemeQuery.data && <div className="mt-6 space-y-6 text-sm"><p className="leading-relaxed text-[hsl(var(--muted-foreground))]">{schemeQuery.data.description}</p><div><p className="mb-2 font-bold">Eligibility signals</p><div className="space-y-2">{schemeQuery.data.eligibilityRules.map((rule) => <SuccessTick key={rule}>{rule}</SuccessTick>)}</div></div><div><p className="mb-2 font-bold">How to apply</p><ol className="space-y-2 text-[hsl(var(--muted-foreground))]">{schemeQuery.data.applicationSteps.map((step, index) => <li key={step} className="flex gap-2"><span className="font-bold text-[hsl(var(--primary))]">{index + 1}.</span>{step}</li>)}</ol></div></div>}</div></div>}
  </div>;
}