export const stateDistricts: Record<string, string[]> = {
  "Andhra Pradesh": [
    "Anantapur",
    "Chittoor",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Visakhapatnam",
    "Vizianagaram",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Tawang",
    "Changlang",
    "East Siang",
    "Lohit",
    "Papum Pare",
    "West Kameng",
  ],
  Assam: [
    "Baksa",
    "Barpeta",
    "Cachar",
    "Dibrugarh",
    "Kamrup Metropolitan",
    "Nagaon",
    "Sonitpur",
    "Tinsukia",
  ],
  Bihar: [
    "Bhagalpur",
    "Gaya",
    "Muzaffarpur",
    "Patna",
    "Purnia",
    "Saran",
    "Vaishali",
  ],
  Chhattisgarh: [
    "Bastar",
    "Bilaspur",
    "Durg",
    "Janjgir-Champa",
    "Korba",
    "Raipur",
    "Rajnandgaon",
  ],
  Goa: ["North Goa", "South Goa"],
  Gujarat: [
    "Ahmedabad",
    "Anand",
    "Gandhinagar",
    "Kutch",
    "Rajkot",
      "Surat",
    "Vadodara",
  ],
  Haryana: [
    "Ambala",
    "Faridabad",
    "Gurugram",
    "Hisar",
    "Karnal",
    "Panipat",
    "Rohtak",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Kangra",
    "Kullu",
    "Mandi",
    "Shimla",
    "Solan",
  ],
  Jharkhand: [
    "Bokaro",
    "Dhanbad",
    "East Singhbhum",
    "Hazaribagh",
    "Ranchi",
    "West Singhbhum",
  ],
  Karnataka: [
    "Bengaluru Urban",
    "Belagavi",
    "Dakshina Kannada",
    "Dharwad",
    "Hubballi",
    "Mangaluru",
    "Mysuru",
    "Shivamogga",
    "Tumakuru",
  ],
  Kerala: [
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Thiruvananthapuram",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Jabalpur",
    "Gwalior",
    "Rewa",
    "Sagar",
    "Ujjain",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Aurangabad",
    "Kolhapur",
    "Mumbai City",
    "Nagpur",
    "Nashik",
    "Pune",
    "Satara",
    "Thane",
  ],
  Manipur: [
    "Bishnupur",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Senapati",
    "Thoubal",
  ],
  Meghalaya: [
    "East Khasi Hills",
    "Jaintia Hills",
    "Ri-Bhoi",
    "South Garo Hills",
    "West Garo Hills",
    "West Khasi Hills",
  ],
  Mizoram: ["Aizawl", "Champhai", "Kolasib", "Lunglei", "Mamit", "Serchhip"],
  Nagaland: ["Dimapur", "Kohima", "Mokokchung", "Mon", "Tuensang", "Wokha"],
  Odisha: [
    "Balasore",
    "Cuttack",
    "Ganjam",
    "Khordha",
    "Mayurbhanj",
    "Puri",
    "Sambalpur",
  ],
  Punjab: [
    "Amritsar",
    "Bathinda",
    "Jalandhar",
    "Ludhiana",
    "Patiala",
    "Sangrur",
  ],
  Rajasthan: [
    "Ajmer",
    "Alwar",
    "Bikaner",
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Udaipur",
  ],
  Sikkim: ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Salem",
    "Tiruchirappalli",
    "Tirunelveli",
    "Vellore",
  ],
  Telangana: [
    "Adilabad",
    "Hyderabad",
    "Karimnagar",
    "Khammam",
    "Nalgonda",
    "Nizamabad",
    "Warangal",
  ],
  Tripura: [
    "Dhalai",
    "Gomati",
    "Khowai",
    "North Tripura",
    "Sepahijala",
    "South Tripura",
    "West Tripura",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Allahabad",
    "Bareilly",
    "Ghaziabad",
    "Gorakhpur",
    "Kanpur Nagar",
    "Lucknow",
    "Meerut",
    "Varanasi",
  ],
  Uttarakhand: [
    "Almora",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Udham Singh Nagar",
  ],
  "West Bengal": [
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "North 24 Parganas",
    "South 24 Parganas",
  ],
  "Andaman and Nicobar Islands": [
    "Nicobar",
    "North and Middle Andaman",
    "South Andaman",
  ],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Dadra and Nagar Haveli",
    "Daman",
    "Diu",
  ],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "South Delhi",
    "West Delhi",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Baramulla",
    "Jammu",
    "Kathua",
    "Srinagar",
    "Udhampur",
  ],
  Ladakh: ["Kargil", "Leh"],
  Lakshadweep: ["Lakshadweep"],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
};

export const states = Object.keys(stateDistricts);

export function districtsForState(state: string) {
  return stateDistricts[state] ?? [];
}
